name: Releases

on:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
         python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install

      - name: Run tests
        run: poetry run pytest -v

      - name: Set environment variables
        shell: powershell
        run: |
          $env:REPO_NAME = $env:GITHUB_REPOSITORY -replace '^.*/'
          $env:RELEASE_VERSION = $env:GITHUB_REF -replace '^refs/tags/'
          echo "REPO_NAME=$env:REPO_NAME" >> $env:GITHUB_ENV
          echo "RELEASE_VERSION=$env:RELEASE_VERSION" >> $env:GITHUB_ENV

      - name: Build binary
        shell: powershell
        run: |
          $binaryName = "$env:REPO_NAME-$env:RELEASE_VERSION"
          echo "BINARY_NAME=$binaryName"
          poetry run pyinstaller -F --name $binaryName main.py

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist\\mafia_allocation-*"
          bodyFile: "CHANGELOG.md"
