name: Releases

on:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
         python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
          poetry add pyinstaller

      - name: Run tests
        run: poetry run pytest -v

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          REPO_NAME=$(basename ${{ github.repository }})
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Build binary
        run: poetry run pyinstaller -F --name $REPO_NAME-$RELEASE_VERSION main.py

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/mafia_allocation-*"
          bodyFile: "CHANGELOG.md"
